config/routes.rb
Rails.application.routes.draw do

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }

  resources :male_betta do
    resources :comments
  end

  resources :users

  resources :orders, only: [:index, :show, :create, :destroy]

  root 'simple_pages#index'

  get 'simple_pages/about'

  get 'simple_pages/contact'

  get 'simple_pages/index'

  post 'simple_pages/thank_you'

  post 'payments/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FancyFins</title>

    <link href="https://fonts.googleapis.com/css?family=Julius+Sans+One|Quicksand" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <!-- Bootstrap core JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
  </head>

  <body data-spy="scroll">
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="projectName navbar-brand">
            <%= link_to "FancyFins", simple_pages_index_path %>
          </div> <!--end projectName-->

        </div> <!--end navbar-header-->
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to "Home", simple_pages_index_path %></li>
            <li><%= link_to "Male Bettas", male_betta_path %></li>
            <li><%= link_to "Orders", orders_path %></li>
            <li>
              <% if user_signed_in? %>
                <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
              <% else %>
                <%= link_to('Login', new_user_session_path) %>
              <% end %>
            </li>
          </ul>
        </div> <!--end navbar-collapse-->
      </div> <!--end container-fluid-->
    </nav>
    <div class="navbar-spacer"></div>

    <% if notice %>
      <div class="container notice alert alert-info">
        <p id="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if alert %>
      <div class="container notice alert alert-warning">
        <div class="col-md-4">
          <img id="alertImg" src="https://i1.wp.com/www.microscopy-uk.org.uk/mag/artnov11macro/daj_website/edit_6.jpg?resize=574%2C630">
        </div>
        <div class="col-md-8">
          <h1> Hey! </h1>
          <h3 id="alert"><%= alert %></h3>
        </div>
      </div>
    <% end %>

    <%= yield %>
    <div class="navbar-spacer"></div>
    <footer>
      <%= form_with(url: male_betta_path, method: 'get', local: true, class: 'nav_search') do |form| %>
        <%= form.text_field :q, id: 'q', value: params[:q], class: 'nav_searchbar', placeholder: 'Search for...' %>
        <%= button_tag(type: 'submit', class: "btn btn-primary, nav_search_submit") do %>
          <span class="glyphicon glyphicon-search"></span>
        <% end %>
      <% end %>
      <div id="copy"> &copy; 2018 Louise Dy Quiangco </div>
    </footer>
  </body>
</html>